<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2ebd0b57-0ef1-4b9c-bad0-7b10a81ddec6</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_to_cart_sauce_labs_backpack</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'add-to-cart-sauce-labs-backpack')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>add-to-cart-sauce-labs-backpack</value>
        <webElementGuid>336f77d3-03a4-4669-8f93-e6d0749abae3</webElementGuid>
    </webElementProperties>
</WebElementEntity>